.TH TUBES 1 tubes-1.4.2
.SH NAME
tubes \- irc pipes
.SH SYNOPSIS
.B tubes
.RB [ \-S ]
.RB [ \-h
.IR host ]
.RB [ \-p
.IR port ]
.SH DESCRIPTION
.B tubes
is a small daemon that provides a minimalistic interface for irc bots.
Messages to and from the host are represented by two FIFO buffers in /tmp.
These buffers are named for the host tubes is connected to, with ".in" or
".out" appended to it for incoming or outgoing messages respectively.

.SH OPTIONS
.TP
.B \-S
Use SSL (changes port to 6697)
.TP
.BI \-h " host"
Use a host other than the default (chat.freenode.net)
.TP
.BI \-p " port"
Use a port other than the default (6667) - this option should be specified
after
.B \-S
if SSL is also desired

.SH FILES
The incoming and outgoing FIFO buffers are stored in /tmp and are named for
the server tubes is connected to with .in or .out appended to the end.
~/.tubes.err is used to store an error string if tubes exits with -1.
.SH EXIT STATUS
Returns 1 on error, 0 on success.
.SH AUTHOR
Copyright \(co 2016 Thomas Mannay <audiobarrier@openmailbox.org>.
